from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

from resume_diagnostics_engine.skill_extractor import extract_explicit_skills
from resume_diagnostics_engine.role_recommender import suggest_roles
from resume_diagnostics_engine.jd_matcher import calculate_jd_match


def generate_resume_report(resume):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)

    styles = getSampleStyleSheet()
    story = []

    # ===== TITLE =====
    story.append(Paragraph("ATS Resume Analysis Report", styles["Title"]))
    story.append(Spacer(1, 12))

    # ===== BASIC INFO =====
    story.append(Paragraph(
        f"<b>User:</b> {resume.user.username}",
        styles["Normal"]
    ))
    story.append(Paragraph(
        f"<b>Uploaded On:</b> {resume.uploaded_at.strftime('%d %b %Y')}",
        styles["Normal"]
    ))
    story.append(Spacer(1, 12))

    # ===== ATS SCORE =====
    if resume.ats_score is not None:
        story.append(Paragraph(
            f"<b>ATS Score:</b> {resume.ats_score}/100",
            styles["Heading2"]
        ))
        story.append(Spacer(1, 10))

    # ===== SUGGESTED ROLE =====
    if resume.suggested_role:
        story.append(Paragraph(
            f"<b>Suggested Role:</b> {resume.suggested_role}",
            styles["Normal"]
        ))
        story.append(Spacer(1, 12))

    # ===== SKILLS ANALYSIS =====
    skills = extract_explicit_skills(resume.extracted_text or "")

    story.append(Paragraph("Detected Skills", styles["Heading2"]))
    if skills:
        story.append(Paragraph(", ".join(skills), styles["Normal"]))
    else:
        story.append(Paragraph("No skills detected", styles["Normal"]))

    story.append(Spacer(1, 14))

    # ===== JOB DESCRIPTION MATCH =====
    if resume.job_description:
        jd_score, missing_keywords = calculate_jd_match(
            resume_text=resume.extracted_text,
            jd_text=resume.job_description
        )

        story.append(Paragraph("Job Description Match", styles["Heading2"]))
        story.append(Paragraph(
            f"JD Match Score: <b>{jd_score}%</b>",
            styles["Normal"]
        ))
        story.append(Spacer(1, 6))

        if missing_keywords:
            story.append(Paragraph(
                "Missing JD Skills:",
                styles["Normal"]
            ))
            story.append(Paragraph(
                ", ".join(missing_keywords),
                styles["Normal"]
            ))
        else:
            story.append(Paragraph(
                "No critical JD skills missing 🎯",
                styles["Normal"]
            ))

        story.append(Spacer(1, 14))

    # ===== ROLE INSIGHT =====
    roles = suggest_roles(skills)

    story.append(Paragraph("Skill Insight", styles["Heading2"]))

    if roles:
        story.append(Paragraph(
            f"Best matched role: <b>{roles[0]}</b>",
            styles["Normal"]
        ))
        story.append(Paragraph(
            "Add more role-specific keywords to improve ATS score.",
            styles["Normal"]
        ))
    else:
        story.append(Paragraph(
            "Insufficient skill data to recommend roles.",
            styles["Normal"]
        ))

    story.append(Spacer(1, 20))

    # ===== FOOTER =====
    story.append(Paragraph(
        "<i>Generated by SkillMatch ATS Engine</i>",
        styles["Italic"]
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer
