# Generated by Django 4.2 on 2026-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_resume_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='has_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='has_experience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='has_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='has_skills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_readable',
            field=models.BooleanField(default=True),
        ),
    ]
