# Generated by Django 4.2 on 2026-01-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_resume_ats_score_resume_has_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='has_education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='has_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='has_projects',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='has_skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='is_readable',
        ),
    ]
