# Generated by Django 4.2 on 2026-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0004_remove_resume_has_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='ats_score',
        ),
        migrations.AlterField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
